apiVersion: v1
data:
  logstash.conf: |-
    input {
      beats {
        port => 5000
      }
    }

    filter {
      if [type] == "kube-logs" {

        mutate {
          rename => ["log", "message"]
        }

        date {
          match => ["time", "ISO8601"]
          remove_field => ["time"]
        }

        grok {
          match => { "source" => "/var/log/containers/%{DATA:pod_name}_%{DATA:namespace}_%{GREEDYDATA:container_name}-%{DATA:container_id}.log" }
          remove_field => ["source"]
        }
      }
    }

    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2017-10-21T20:37:21Z
  name: logstash-config
  namespace: default
  resourceVersion: "1714"
  selfLink: /api/v1/namespaces/default/configmaps/logstash-config
  uid: a3123f17-b69f-11e7-a5b2-080027b6cdce
